version: '3'
services:
  web:
    build: .
    volumes:
      - .:/taskleaf
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub

  db:
    image: postgres
    volumes:
      - psg_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  
  selenium_chrome:
    image: selenium/standalone-chrome
    logging:
      driver: none

volumes:
  psg_volume: