version: '3'
services:
  web:
    build: .
    volumes:
      - .:/taskleaf
    command: sh -c "rm -f tmp/pids/server.pid && rails s --environment=production -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SELENIUM_DRIVER_URL=$SELENIUM_DRIVER_URL
      - RAILS_SERVE_STATIC_FILES=1

  db:
    image: postgres
    volumes:
      - psg_volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=taskleaf
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TASKLEAF_DATABASE_PASSWORD=$TASKLEAF_DATABASE_PASSWORD
  
  selenium_chrome:
    image: selenium/standalone-chrome
    logging:
      driver: none

volumes:
  psg_volume: